### ISSUE TITLE
rgbKit.UseAura(); Error

### ISSUE THREAD

**Issue by tew515** [RGBKit/rgbkit#5]
Using the sample code: https://github.com/RGBKit/rgbkit/wiki/Getting-Started

![image](https://user-images.githubusercontent.com/67100537/88564860-aba35280-d02b-11ea-87c0-a3ded9eb1779.png)
![image](https://user-images.githubusercontent.com/67100537/88590685-0ef4ab00-d053-11ea-95d3-d0e3a8651952.png)

System.Runtime.InteropServices.COMException
  HResult=0x80040154
  Message=Retrieving the COM class factory for component with CLSID {05921124-5057-483E-A037-E9497B523590} failed due to the following error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)).
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at RGBKit.Providers.Aura.AuraDeviceProvider..ctor()
   at RGBKit.Core.AuraDeviceProviderExtensions.UseAura(IRGBKitService rgbKit)
   at Voice.NETSatnddard2._1.Program.Main(String[] args) in C:\Users\tomwh\source\repos\Voice.NETSatnddard2.1\Voice.NETSatnddard2.1\Program.cs:line 16

Any help would be appreciated. Thank you.

**Comment by AndrewBabbitt97** [comment]
Looks like the Aura COM components aren't installed correctly on your machine. Please reinstall the latest version of Aura or Armory Crate.
